version: 0.1.{build}
environment:
  packageVersion: '0.1.0'
image: Visual Studio 2013
configuration: Release
pull_requests:
  do_not_increment_build_number: true
init:
- ps: $env:buildVersion = "$env:packageVersion.$env:appveyor_build_number"
- ps: $env:nugetVersion = "$env:packageVersion-beta-$env:appveyor_build_number"
- ps: Update-AppveyorBuild -Version $env:buildVersion
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(buildVersion)'
  assembly_file_version: '$(buildVersion)'
  assembly_informational_version: '$(nugetVersion)'
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
cache:
- packages -> **\packages.config
before_build:
- cmd: nuget restore src/RequestLogger.sln
build:
  project: src/RequestLogger.sln
  verbosity: minimal
after_build:
- ps: nuget pack src/RequestLogger/RequestLogger.csproj -version "$env:nugetVersion" -Prop Configuration="$env:CONFIGURATION"
- ps: nuget pack src/RequestLogger.NLog/RequestLogger.NLog.csproj -version "$env:nugetVersion" -Prop Configuration="$env:CONFIGURATION"
- ps: nuget pack src/RequestLogger.Web/RequestLogger.Web.csproj -version "$env:nugetVersion" -Prop Configuration="$env:CONFIGURATION"
artifacts:
- path: '*.nupkg'
  name: NuGet
deploy:
- provider: NuGet
  server: https://www.myget.org/F/package-hub/api/v2/package
  api_key:
    secure: qtaJZ+3ZB2B9iniOMBkLcNDFEfYBKwmqPD8svppaLlec2lhEZVKQb9hu38MWFMD4
  skip_symbols: false
  on:
    branch: master
    appveyor_repo_tag: true
